version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: echo "Testing..."
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: echo "Buidling..."
  deploy:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: echo "Deploying..."
workflows:
  version: 2
  my_perfect_workflow1:
    jobs:
      - test
      - build
        requires:
          - test
      - deploy
        requires:
          - build