version: 2

default: &default
  docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dummy-{{ checksum "dummy-info.json" }}
      - save_cache:
          paths:
            - dummy_dir
          key: dummy-{{ checksum "dummy-info.json" }}

jobs:
  test:
    <<: *default
    steps:
      - run: echo "Testing..."
  build:
    <<: *default
    steps:
      - run: echo "Buidling..."
  deploy:
    <<: *default
    steps:
      - run: echo "Deploying..."
workflows:
  version: 2
  my_perfect_workflow:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build