version: 2
jobs:
  job1:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world1"
  job2:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world2"
workflows:
  version: 2
  my_perfect_workflow1:
    jobs:
      - job1
      - job2
  my_perfect_workflow2:
    jobs:
      - job1
      - job2